export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
export const FETCH_POST_BY_ID = "FETCH_POST_BY_ID";

export const DELETE_POST = 'DELETE_POST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';
export const DELETE_POST_START = 'DELETE_POST_START';

export const FILTER_POST_USERNAME = "FILTER_POST_USERNAME";
export const SHOW_ALL = "SHOW_ALL"

export const ADD_COMMENT = "ADD_COMMENT";
export const FETCH_COMMENTS_SUCCESS = "FETCH_COMMENTS_SUCCESS";

export const FILTER_TAGS = "FILTER_TAGS";